# Site settings
title: Victor Alencastro - Front End Developer
description: Victor Alencastro - Front End Developer - Desenvolvedor Front End de Hortol√¢ndia para o mundo.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://victoralencastro.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Victor Alencastro
user_description: Front End Developer / UX Designer
user_title: Victor Alencastro
email: vicfelipe@live.com
twitter_username: https://twitter.com/VictorAlencast2
github_username:  https://github.com/vicfelipe
gplus_username:  https://plus.google.com/u/0/100908083867746365378
disqus_username: https://disqus.com/by/victoralencastro/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
