name: Victor Alencastro
description: Desenvolvedor Front-end
meta_description: "Victor Alencastro, Desenvolvedor Front-End. Hortol√¢ndia/SP"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://victoralencastro.com.br'
google_analytics: 'UA-69169825-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://victoralencastro.com.br'
author:         'Victor Alencastro'
